eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9000
spring:
  application:
    name: api-gateway
zuul:
#  ignored-services:
  ignored-patterns: /*-service/**
  routes:
    order-service: /apigateway/order/**
    product-service: /apigateway/product/**
  sensitive-headers:
